apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: 'service-applicationset-{{ .Release.Namespace }}'
  namespace: argocd
spec:
  generators:
    - git:
        # git repository to get the variables from
        repoURL: https://github.com/stufegdzic/customers.git
        # branch used to get the variables from
        revision: demo
        files:
          # path to the directory that includes directories to read as variables
          - path: {{ .Release.Namespace }}/**/config-service.yaml
  template:
    metadata:
      # basename is the name of the directory not the full path
      name: '{{ .Release.Namespace }}-{{ print "{{type}}" }}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        # source repo, in this example both repositories are the same
        repoURL: https://github.com/stufegdzic/resources-templates.git
        targetRevision: demo
        # path to read manifests from, here it's the full path not only the name of the directory
        path: service-template/{{ print "{{type}}" }}
        helm:
          valueFiles:
            - 'values.yaml'
          values: |-
            {{ print "{{values}}" }}
            type: {{ print "{{ type }}" }}
      destination:
        server: https://kubernetes.default.svc
        # different namespaces named after the directories names to be used as destinations
        namespace: '{{ .Release.Namespace }}'